# Generated by Django 3.2 on 2021-04-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='comment',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
