# Generated by Django 3.2 on 2021-04-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0002_alter_event_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
