# Generated by Django 3.2.1 on 2021-07-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, default='default_pet_profile.png', null=True, upload_to='images/'),
        ),
    ]
