# Generated by Django 3.2 on 2021-04-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, default='default-pet.png', null=True, upload_to='images/'),
        ),
    ]
