# Generated by Django 3.2.1 on 2021-07-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0002_alter_pet_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, default='mypet/img/default_pet_profile.png', null=True, upload_to='images/'),
        ),
    ]
