# Generated by Django 3.2 on 2021-04-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0002_alter_pet_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('cat', 'Chat'), ('dog', 'Chien')], max_length=50),
        ),
    ]
