# Generated by Django 3.2.5 on 2021-07-27 10:53

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0004_alter_pet_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/2021-07-27'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('cat', 'Chat'), ('dog', 'Chien'), ('bird', 'Bird'), ('rabbit', 'Lapin')], max_length=50),
        ),
    ]
