# Generated by Django 3.2.5 on 2021-07-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0005_auto_20210727_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('cat', 'Chat'), ('dog', 'Chien'), ('bird', 'Oiseau'), ('rabbit', 'Lapin')], max_length=50),
        ),
    ]
