# Generated by Django 3.2.13 on 2022-06-14 15:39

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0006_alter_pet_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/2022-06-14'),
        ),
    ]
