# Generated by Django 3.2 on 2021-04-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0006_alter_pet_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, default='./static/mypet/img/default_pet_profile.png', null=True, upload_to='images/'),
        ),
    ]
